"""empty message

Revision ID: 334261b2868f
Revises: bbae8f2b06b1
Create Date: 2025-07-25 15:58:11.223026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334261b2868f'
down_revision: Union[str, Sequence[str], None] = 'bbae8f2b06b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_details', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_details', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('user_details', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_details', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_details', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('user_details', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
