"""empty message

Revision ID: 7f0582b7c5ae
Revises: f40b27d551fc
Create Date: 2025-07-23 13:36:45.609338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0582b7c5ae'
down_revision: Union[str, Sequence[str], None] = 'f40b27d551fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_current_drivers_active'), table_name='current_drivers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_current_drivers_active'), 'current_drivers', ['active'], unique=False)
    # ### end Alembic commands ###
