"""empty message

Revision ID: bbae8f2b06b1
Revises: 9351a38645c6
Create Date: 2025-07-25 15:55:14.615445

"""
from typing import Sequence, Union
import sqlmodel as sm
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbae8f2b06b1'
down_revision: Union[str, Sequence[str], None] = '9351a38645c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sm.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sm.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sm.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('user_details',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sm.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('fav_driver', sm.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fav_constructor', sm.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sm.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prediciton_points', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['fav_constructor'], ['current_constructors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fav_driver'], ['current_drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_details_country'), 'user_details', ['country'], unique=False)
    op.create_index(op.f('ix_user_details_dob'), 'user_details', ['dob'], unique=False)
    op.create_index(op.f('ix_user_details_fav_constructor'), 'user_details', ['fav_constructor'], unique=False)
    op.create_index(op.f('ix_user_details_fav_driver'), 'user_details', ['fav_driver'], unique=False)
    op.create_index(op.f('ix_user_details_name'), 'user_details', ['name'], unique=False)
    op.create_index(op.f('ix_user_details_user_id'), 'user_details', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_details_user_id'), table_name='user_details')
    op.drop_index(op.f('ix_user_details_name'), table_name='user_details')
    op.drop_index(op.f('ix_user_details_fav_driver'), table_name='user_details')
    op.drop_index(op.f('ix_user_details_fav_constructor'), table_name='user_details')
    op.drop_index(op.f('ix_user_details_dob'), table_name='user_details')
    op.drop_index(op.f('ix_user_details_country'), table_name='user_details')
    op.drop_table('user_details')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
