"""empty message

Revision ID: d13c2507dd7e
Revises: 5ec5c8f1889f
Create Date: 2025-07-23 17:40:20.216968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel as sm

# revision identifiers, used by Alembic.
revision: str = 'd13c2507dd7e'
down_revision: Union[str, Sequence[str], None] = '5ec5c8f1889f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_constructors',
    sa.Column('id', sm.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sm.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nationality', sm.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('curr_points', sa.Integer(), nullable=False),
    sa.Column('curr_pos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_current_constructors_curr_points'), 'current_constructors', ['curr_points'], unique=False)
    op.create_index(op.f('ix_current_constructors_curr_pos'), 'current_constructors', ['curr_pos'], unique=False)
    op.create_index(op.f('ix_current_constructors_name'), 'current_constructors', ['name'], unique=False)
    op.create_index(op.f('ix_current_constructors_nationality'), 'current_constructors', ['nationality'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_current_constructors_nationality'), table_name='current_constructors')
    op.drop_index(op.f('ix_current_constructors_name'), table_name='current_constructors')
    op.drop_index(op.f('ix_current_constructors_curr_pos'), table_name='current_constructors')
    op.drop_index(op.f('ix_current_constructors_curr_points'), table_name='current_constructors')
    op.drop_table('current_constructors')
    # ### end Alembic commands ###
