"""empty message

Revision ID: e1606e8264b3
Revises: d9e678e935b1
Create Date: 2025-07-14 03:29:14.113637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel as sm

# revision identifiers, used by Alembic.
revision: str = 'e1606e8264b3'
down_revision: Union[str, Sequence[str], None] = 'd9e678e935b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sm.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nationality', sm.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seasons', sm.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('drivers_championships', sa.Integer(), nullable=False),
    sa.Column('race_entries', sa.Integer(), nullable=False),
    sa.Column('race_starts', sa.Integer(), nullable=False),
    sa.Column('pole_positions', sa.Integer(), nullable=False),
    sa.Column('race_wins', sa.Integer(), nullable=False),
    sa.Column('podiums', sa.Integer(), nullable=False),
    sa.Column('fastest_laps', sa.Integer(), nullable=False),
    sa.Column('points', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_driver_name'), 'drivers', ['driver_name'], unique=False)
    op.create_index(op.f('ix_drivers_drivers_championships'), 'drivers', ['drivers_championships'], unique=False)
    op.create_index(op.f('ix_drivers_fastest_laps'), 'drivers', ['fastest_laps'], unique=False)
    op.create_index(op.f('ix_drivers_nationality'), 'drivers', ['nationality'], unique=False)
    op.create_index(op.f('ix_drivers_podiums'), 'drivers', ['podiums'], unique=False)
    op.create_index(op.f('ix_drivers_points'), 'drivers', ['points'], unique=False)
    op.create_index(op.f('ix_drivers_pole_positions'), 'drivers', ['pole_positions'], unique=False)
    op.create_index(op.f('ix_drivers_race_entries'), 'drivers', ['race_entries'], unique=False)
    op.create_index(op.f('ix_drivers_race_starts'), 'drivers', ['race_starts'], unique=False)
    op.create_index(op.f('ix_drivers_race_wins'), 'drivers', ['race_wins'], unique=False)
    op.create_index(op.f('ix_drivers_seasons'), 'drivers', ['seasons'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drivers_seasons'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_race_wins'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_race_starts'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_race_entries'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_pole_positions'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_points'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_podiums'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_nationality'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_fastest_laps'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_drivers_championships'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_driver_name'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
