"""empty message

Revision ID: f40b27d551fc
Revises: 27750caa3f64
Create Date: 2025-07-23 13:00:09.064546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel as sm

# revision identifiers, used by Alembic.
revision: str = 'f40b27d551fc'
down_revision: Union[str, Sequence[str], None] = '27750caa3f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_drivers',
    sa.Column('id', sm.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('perm_number', sa.Integer(), nullable=False),
    sa.Column('code', sm.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sm.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dob', sm.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nationality', sm.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_current_drivers_active'), 'current_drivers', ['active'], unique=False)
    op.create_index(op.f('ix_current_drivers_code'), 'current_drivers', ['code'], unique=False)
    op.create_index(op.f('ix_current_drivers_dob'), 'current_drivers', ['dob'], unique=False)
    op.create_index(op.f('ix_current_drivers_full_name'), 'current_drivers', ['full_name'], unique=False)
    op.create_index(op.f('ix_current_drivers_nationality'), 'current_drivers', ['nationality'], unique=False)
    op.create_index(op.f('ix_current_drivers_perm_number'), 'current_drivers', ['perm_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_current_drivers_perm_number'), table_name='current_drivers')
    op.drop_index(op.f('ix_current_drivers_nationality'), table_name='current_drivers')
    op.drop_index(op.f('ix_current_drivers_full_name'), table_name='current_drivers')
    op.drop_index(op.f('ix_current_drivers_dob'), table_name='current_drivers')
    op.drop_index(op.f('ix_current_drivers_code'), table_name='current_drivers')
    op.drop_index(op.f('ix_current_drivers_active'), table_name='current_drivers')
    op.drop_table('current_drivers')
    # ### end Alembic commands ###
